print("Available Stripe practice problems:")
print("1. Transaction Normalizer")
print("2. Fraudulent Charge Detector")
print("3. Charge Aggregator")
print("4. Refund Processor")
print("5. Idempotent API Calls")
print("6. Log Compression")
print("7. Rate Limiter")
print("\nOpen any of these files and run it directly in VS Code to practice like LeetCode.")
